#' aboutExample UI Function
#'
#' @title mod_aboutExample_ui mod_aboutExample_server
#'
#' @description A shiny Module. This module generates information for the 
#' example data that is pre-loaded when the application launches. 
#'
#'@param id,input,output,session Internal parameters for {shiny}.#'
#'
#'@noRd
#'
#' @importFrom shiny NS tagList
mod_aboutExample_ui <- function(id) {
  ns <- NS(id)
  tagList(
    fluidRow(column(12, offset = 0,
                    mainPanel(h2(strong("Description of Example Data")),
                              tags$br(),
                              tags$strong("Three example datasets are included
                                          to test out the application."),
                              tags$p("The three datasets hopefully highlight how
                              to best use the application.",
                                     tags$br(),
                                     "Data descriptions below.",
                                     tags$br(),
                                     tags$br(),
                                     tags$strong("How to test with example data"
                                     ),
                                     tags$br(),
                                     "The best way to get going with the example
                                     data is to select all three files (tree,
                                     genetic, and meta) and press the
                                     'Add Tree button'. This will display the
                                     tree and allow you to start adjusting
                                     the tree visualization paramters
                                     immediately.",
                                     tags$br(),
                                     tags$br(),
                                     "If you want to add annotations then
                                     highlight the tip labels to their
                                     most recent common ancestor,",
                                     tags$a("MRCA", href =
                                              "https://evolution.berkeley.edu/evolibrary/article/phylogenetics_02"),
                                     ", and press the 'Add Annotations' button.
                                     Repeat until you are satisfied."),
                              "If you want to remove previously placed
                              annotations, just press the 'Remove Annotations'
                              button, this will step your annotations back one
                              by one.",
                              tags$br(),
                              tags$br(),
                              "If you want to see what the heatmap looks like
                              this is only part of example data 3 and will
                              automatically load/unload if you press the
                              'Add Matrix/Remove Matrix' buttons.",
                              tags$br(),
                              tags$br(),
                              tags$p((tags$h5(tags$strong("Data set 1"))),
                                     "This data set will automatically be
                                     seen when a user presses the 'Add Tree'
                                     button.",
                                     tags$li(tags$em("example tree 1")),
                                     "This is a newick formatted tree with
                                     19 tip labels ",
                                     tags$li(tags$em("example gene 1")),
                                     "This is a genetic distance matrix saved
                                     as a tsv file with the same corresponding
                                     tips found in the example tree 1.",
                                     tags$li(tags$em("example meta 1")),
                                     "This is a meta data file used for
                                     correcting the tip labels which contains
                                     two columns and is a csv file."),
                              tags$br(),
                              tags$br(),
                              tags$p((tags$h5(tags$strong("Data set 2"))),
                                     "This data set will automatically be
                                     seen when a user presses the 'Add Tree'
                                     button.",
                                     tags$li(tags$em("example tree 2")),
                                     "This is a newick formatted tree with
                                     14 tip labels generated by RAxML.",
                                     tags$li(tags$em("example gene 2")),
                                     "This is a genetic distance matrix saved
                                     as a tsv file with the same corresponding
                                     tips found in the example tree 2.",
                                     tags$li(tags$em("example meta 2")),
                                     "This is a meta data file used for
                                     correcting the tip labels which contains
                                     two columns and is a tsv file."),
                              tags$br(),
                              tags$br(),
                              tags$p((tags$h5(tags$strong("Data set 3"))),
                                     "This data set will automatically be
                                     seen when a user presses the 'Add Tree'
                                     button.",
                                     tags$li(tags$em("example tree 3")),
                                     "This is a newick formatted tree with
                                     14 tip labels.",
                                     tags$li(tags$em("example gene 3")),
                                     "This is a genetic distance matrix saved
                                     as a tsv file with the same corresponding
                                     tips found in the example tree 2.",
                                     tags$li(tags$em("example meta 3")),
                                     "This is a meta data file used for
                                     correcting the tip labels and plotting a
                                     heatmap. This file has three columns and
                                     is a txt file.")
                    )))
  )
}

#' aboutExample Server Function
#'
#' @noRd
mod_aboutExample_server <- function(input, output, session) {
  ns <- session$ns

}
